### ISSUE TITLE
slackChannelId 옵션명 변경 요청

### ISSUE THREAD

**Issue by lineaheshsh** [naver/notify-pr-line-count#6]
안녕하세요!

해당 Action 사용을 하다 2가지 정도 개선이 되었으면 좋을 것 같아 제보드립니다.

**[제보 내용]**
- slackChannelId 옵션명에서 Id를 빼거나 수정이 되면 좋을 것 같습니다.(네이밍 변경 요청)
- slackMessage 결과를 Console 로 출력이 되면 좋을 것 같습니다.

**[Description]**
slackChannelId에 Channel Id 값을 넣으니 메세지가 정상적으로 전송이 되지 않습니다.
그런데 Action은 성공이 된 상태로 끝나서 curl 형태로 메세지를 날려보니 아래와 같이 전송이 실패 된 것을 알 수 있었습니다.
`{"ok":false,"error":"channel_not_found","warning":"missing_charset","response_metadata":{"warnings":["missing_charset"]}}`

소스를 확인해보니 `channelId` 부분에 `#`이 붙는걸 확인했고 채널명으로 전송하니 정상적으로 전송이 되는 것을 확인 했습니다.
``` javascript
const sendMessage = async ({repoName, title, url, channelId, maxChanges}) => {
  return axios({
    method: "post",
    headers: {
      Authorization: `Bearer ${core.getInput("slackBotToken")}`,
      "Content-Type": "application/json"
    },
    url: "https://slack.com/api/chat.postMessage",
    data: {
      channel: `#${channelId}`,   // <- #이 있어 Chaennel ID 입력 시 메세지 전송이 되지 않음.
      blocks: [
      ...
    }
```

현재 `slackChannelId` 옵션의 경우 네이밍에 `Id`가 포함되어 있다보니 저와 같은 실수를 하시는 분들이 꽤 있으실 것 같아요.
마지막으로 편리한 기능 만들어주셔서 감사합니다 :)

**Comment by ygnoh** [comment]
안녕하세요 @lineaheshsh 님!

의견 감사드립니다.
내부적으로 검토하고 답변 드리겠습니다.

**Comment by lineaheshsh** [comment]
그리고 Tag 정보도 오타가 있는 듯 합니다! `lastest -> latest`

**Comment by ygnoh** [comment]
> 그리고 Tag 정보도 오타가 있는 듯 합니다! `lastest -> latest`

제보 감사합니다 이건 수정했습니다

**Comment by ygnoh** [comment]
@lineaheshsh 님 안녕하세요

말씀해 주신 두 부분 수정하여 1.1.0 버전 배포했습니다. 이슈 있다면 말씀해 주세요!
